[package]
name = "h3-happy-eyeballs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = "0.7"
quiche = "0.10"
url = "2.2"
